### ISSUE TITLE
Allow multiple shm segments, or use mmap or whatever to overcome the kernel shm segment size limit

### ISSUE THREAD

**Issue by teo1978** [eaccelerator/eaccelerator#52]
From https://github.com/eaccelerator/eaccelerator/wiki/Settings#eacceleratorshm_size

> On Linux the maximum amount of memory a process can allocate is limited by the number set in /proc/sys/kernel/shmmax. Allocating more than this value will result in eAccelerator failing to initialize. The size in this file is given in bytes. You can raise this amount with:
> echo value > /proc/sys/kernel/shmmax 

This is fucking ridiculous. You should allow to use multiple shm segments, and provide a setting for the number of segments to use, as other decent opcode caches do. By the way, some of them (namely XCache) use mmap so you don't have a limit at all.

**Comment by katmai** [comment]
you should post this in the neweracracker fork. that one is being actively maintained.

**Comment by teo1978** [comment]
Wow, could you please at least update the home page at http://eaccelerator.net/ with a link to that fork, so that other people won't waste their time like I did?

**Comment by katmai** [comment]
no because i don't own it. i just directed you to that fork because that guy keeps updating it regularly.

**Comment by teo1978** [comment]
Then at least merge either or both of these pull requests:
https://github.com/eaccelerator/eaccelerator.github.com/pull/1
https://github.com/eaccelerator/eaccelerator/commit/fa49d05486872a1d4a5bab42162bed76bb5b0678

By keeping this dead project there without warning the user that it is unmaintained *and* broken, you are actually making more harm than good. People keep wasting their time installing it. 

Why you don't want to inform people that there exists a maintained version is beyond me (it would make your work useful to people as opposed to harmful), but if you don't want to, at least the documentation should clearly state that this project is deprecated.

**Comment by katmai** [comment]
stop acting like a child. i just told you i don't own the project. the owner is afk for a bunch of years now, so the only useful thing that we can do right now, is just mention the neweracracker fork and direct people there. use that and collaborate there.

peace.

**Comment by teo1978** [comment]
Sorry I thought you were telling me that you don't own neweracracker

**Comment by NewEraCracker** [comment]
Hello,

My fork provides better compatibility as I've merged all tweaks (that I've seen to be suitable) made by other developers, applied my own custom code and removed the broken optimizer.

I am only doing little maintenance to the project and will not introduce any new functionality unless a good Pull-Request is supplied to me that fulfills those specific needs and I confirm it is working on my environments.

I only did my own fork because my environments and certain customers of mine have very specific needs and released it for free to the community for everyone's benefit.

I don't own this official page and developers have been away for a long time with no reply to any messages I sent them.

Please note this project is deprecated anyhow and there are better solutions such as Zend OPcache.

Regards,
NewEraCracker
